spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inscriptionDB?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: THink..ALL1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

